select * from dataset_1;
select weather,temperature from dataset_1;
select * from dataset_1 limit 10;
select distinct passanger from dataset_1;
select * from dataset_1 where destination = 'Home';
select * from dataset_1 order by coupon;
select destination as Destination from dataset_1;
select occupation from dataset_1 group by occupation;
select weather,AVG(temperature)as Avg_temp from dataset_1 group by weather;
select weather,COUNT(temperature) as count_temp from dataset_1 group by weather;
select weather,COUNT(DISTINCT temperature) as count_dist_temp from dataset_1 group by weather;
select weather,SUM(temperature) as sum_temp from dataset_1 group by weather;
select weather,MIN(temperature) as min_temp from dataset_1 group by weather; 
select weather,MAX(temperature) as max_temp from dataset_1 group by weather;
select occupation from dataset_1 group by occupation having occupation = 'Student';
select destination,passanger from (select * from dataset_1 where passanger ='Alone');
select * from dataset_1 where weather like 'sun%';
SELECT DISTINCT temperature from dataset_1 where temperature BETWEEN 29 AND 75;
SELECT occupation from dataset_1 where occupation IN ('Sales & Related');
SELECT occupation from dataset_1 where occupation IN ('Sales & Related','Management');